name: dsi_participant
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.1.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - aom=3.7.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - astunparse=1.6.3
  - attrs=23.2.0
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - blinker=1.7.0
  - blosc=1.21.5
  - bokeh=3.4.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.27.0
  - c-blosc2=2.14.3
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - clarabel=0.7.1
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cvxopt=1.3.2
  - cvxpy=1.4.2
  - cvxpy-base=1.4.2
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.2.0
  - dask-core=2024.2.0
  - dask-expr=0.4.1
  - datasets=2.14.4
  - dav1d=1.2.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.7
  - distributed=2024.2.0
  - docopt=0.6.2
  - dsdp=5.8
  - ecos=2.0.13
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fancyimpute=0.7.0
  - ffmpeg=6.1.1
  - fftw=3.3.10
  - filelock=3.13.3
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.50.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - gast=0.5.4
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.42
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.3.0
  - gnutls=3.7.9
  - google-auth=2.29.0
  - google-auth-oauthlib=1.2.0
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - greenlet=3.0.3
  - grpcio=1.59.3
  - gsl=2.7
  - h5py=3.10.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - huggingface_hub=0.22.2
  - icu=73.2
  - idna=3.6
  - imagecodecs=2024.1.1
  - imageio=2.34.0
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jasper=4.2.3
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jsonpickle=3.0.2
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jxrlib=1.1
  - keras=2.15.0
  - kiwisolver=1.4.5
  - knnimpute=0.1.0
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.3
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libavif16=1.0.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libhwloc=2.9.3
  - libhwy=1.1.0
  - libiconv=1.17
  - libidn2=2.3.7
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libopencv=4.9.0
  - libopenvino=2023.2.0
  - libopenvino-auto-batch-plugin=2023.2.0
  - libopenvino-auto-plugin=2023.2.0
  - libopenvino-hetero-plugin=2023.2.0
  - libopenvino-ir-frontend=2023.2.0
  - libopenvino-onnx-frontend=2023.2.0
  - libopenvino-paddle-frontend=2023.2.0
  - libopenvino-pytorch-frontend=2023.2.0
  - libopenvino-tensorflow-frontend=2023.2.0
  - libopenvino-tensorflow-lite-frontend=2023.2.0
  - libopus=1.3.1
  - libosqp=0.6.3
  - libparquet=15.0.0
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.24.4
  - libqdldl=0.1.7
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.6
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=18.1.2
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - metis=5.1.0
  - missingno=0.5.2
  - ml_dtypes=0.2.0
  - mpfr=4.2.1
  - msgpack-python=1.0.7
  - multidict=6.0.5
  - multiprocess=0.70.15
  - munch=4.0.0
  - munkres=1.1.4
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - nose=1.3.7
  - numba=0.59.1
  - oauthlib=3.2.2
  - opencv=4.9.0
  - openh264=2.4.0
  - openjpeg=2.5.2
  - openssl=3.2.1
  - opt_einsum=3.3.0
  - orc=1.9.2
  - osqp=0.6.3
  - p11-kit=0.24.1
  - packaging=24.0
  - parso=0.8.3
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - plotly=5.19.0
  - pluggy=1.4.0
  - prompt-toolkit=3.0.42
  - protobuf=4.24.4
  - psutil=5.9.8
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-opencv=4.9.0
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.22
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytest=8.1.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.19.1
  - python-flatbuffers=24.3.25
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qdldl-python=0.1.7.post0
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.34.0
  - regex=2023.12.25
  - requests=2.31.0
  - requests-oauthlib=2.0.0
  - rpds-py=0.18.0
  - rsa=4.9
  - sacred=0.8.5
  - safetensors=0.4.2
  - scikit-image=0.22.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - scs=3.2.4.post1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.2.0
  - shap=0.44.1
  - six=1.16.0
  - slicer=0.0.7
  - smmap=5.0.0
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - sqlalchemy=2.0.27
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - suitesparse=5.10.1
  - svt-av1=1.8.0
  - tbb=2021.11.0
  - tblib=3.0.0
  - tenacity=8.2.3
  - tensorboard=2.15.2
  - tensorboard-data-server=0.7.0
  - tensorflow=2.15.0
  - tensorflow-base=2.15.0
  - tensorflow-estimator=2.15.0
  - termcolor=2.4.0
  - threadpoolctl=3.4.0
  - tifffile=2024.2.12
  - tk=8.6.13
  - tokenizers=0.15.2
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.2
  - transformers=4.39.3
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - werkzeug=3.0.2
  - wheel=0.43.0
  - wrapt=1.14.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - beautifulsoup4==4.12.3
      - faraway==0.0.6
      - formulaic==1.0.1
      - frozendict==2.4.0
      - future==1.0.0
      - html5lib==1.1
      - interface-meta==1.3.0
      - islp==0.3.22
      - l0bnb==1.0.0
      - lifelines==0.28.0
      - lightning-utilities==0.11.1
      - llvmlite==0.42.0
      - lxml==5.1.0
      - mpmath==1.3.0
      - multitasking==0.0.11
      - networkx==3.2.1
      - numpy==1.24.4
      - pandas==1.5.3
      - peewee==3.17.1
      - progressbar2==4.4.2
      - pygam==0.9.0
      - python-utils==3.8.2
      - pytorch-lightning==2.2.1
      - soupsieve==2.5
      - sympy==1.12
      - torch==2.2.1
      - torchmetrics==1.3.2
      - webencodings==0.5.1
      - yfinance==0.2.37  